# This is a basic workflow to help you get started with Actions

name: xiaoqi-note

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 安装node服务
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: "14.x"
      
      # 安装依赖
      - name: install dep
        run: npm install
      
      # 打包
      - name: build app 
        run: npm run build
      
      # 上传dist包
      #- name: copy dist file with scp
        #uses: appleboy/scp-action@v0.0.1
        #with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          #port: ${{ secrets.PORT }}
          #source: "docs/"
          #target: "${{secrets.TARGET}}"
          
      # 上传到github page
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
        
        
      
